<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Momentum.Messaging.Abstractions</RootNamespace>
    <PackageId>Momentum.Messaging.Abstractions</PackageId>
    <Description>Transport and serialization contracts for Momentum.Messaging.</Description>
  </PropertyGroup>

</Project>
